SELECT * FROM NASS.nassCensus2012Local WHERE SECTOR_DESC = "ENVIRONMENTAL" ;

SELECT Count(row_names) from nassCensus2012Local;

SELECT DISTINCT SHORT_DESC FROM nassCensus2012Local ORDER BY SHORT_DESC;

SELECT DISTINCT SECTOR_DESC FROM nassCensus2012Local ORDER BY SECTOR_DESC;

SELECT SECTOR_DESC, count(distinct SHORT_DESC) FROM nassCensus2012Local Group BY SECTOR_DESC order by SECTOR_DESC;

SELECT distinct SHORT_DESC FROM nassCensus2012Local WHERE SECTOR_DESC = "ENVIRONMENTAL" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2012Local WHERE SECTOR_DESC = "ECONOMICS" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2012Local WHERE SECTOR_DESC = "ANIMALS & PRODUCTS" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2012Local WHERE SECTOR_DESC = "DEMOGRAPHICS" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2012Local WHERE SECTOR_DESC = "CROPS" order by SHORT_DESC;



#Livestock
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%`  
FROM nassCensus2012Local WHERE 
((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon')) AND
((COMMODITY_DESC ='CATTLE') OR (COMMODITY_DESC = 'SHEEP'))
GROUP BY 
SHORT_DESC, COUNTY_NAME;


#LivestockStatewide
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%`  FROM nassCensus2012Local WHERE 
((STATE_NAME = 'Oregon')) AND
((COMMODITY_DESC ='CATTLE') OR (COMMODITY_DESC = 'SHEEP'))
GROUP BY 
SHORT_DESC, COUNTY_NAME;

#Pasture
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` 
FROM nassCensus2012Local WHERE 
((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon')) AND
((SHORT_DESC ='AG LAND CROPLAND - ACRES') OR 
	(SHORT_DESC ='AG LAND WOODLAND PASTURED - ACRES') OR 
	(SHORT_DESC = 'AG LAND CROPLAND PASTURED ONLY - ACRES') OR
    (SHORT_DESC = 'AG LAND PASTURELAND (EXCL CROPLAND & WOODLAND) - ACRES') OR
    (SHORT_DESC = 'AG LAND IRRIGATED - ACRES') OR
    (SHORT_DESC = 'AG LAND CROPLAND HARVESTED IRRIGATED - ACRES') OR
    (SHORT_DESC = 'AG LAND (EXCL HARVESTED CROPLAND) IRRIGATED - ACRES') OR
    (SHORT_DESC = 'AG LAND PASTURELAND - ACRES') OR
    (SHORT_DESC = 'AG LAND WOODLAND PASTURED - ACRES')
)
GROUP BY 
SHORT_DESC, COUNTY_NAME;







SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` 
FROM nassCensus2012Local WHERE
(COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon') AND
  Short_desc LIKE '%VALUE%'
  GROUP BY 
SHORT_DESC, COUNTY_NAME;




###########  Hay
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` FROM nassCensus2012Local WHERE 
((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon')) AND
((SHORT_DESC ='HAY & HAYLAGE - ACRES HARVESTED') OR 
	(SHORT_DESC = 'HAY & HAYLAGE - OPERATIONS WITH AREA HARVESTED') OR
    (SHORT_DESC = 'HAY & HAYLAGE - PRODUCTION MEASURED IN TONS DRY BASIS')
)
GROUP BY 
SHORT_DESC, COUNTY_NAME;



#Finances
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` 
FROM nassCensus2012Local WHERE 
((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon')) AND
	((SHORT_DESC ='ANIMAL TOTALS (EXCL BREEDING) - EXPENSE MEASURED IN $') OR 
	(SHORT_DESC = 'ANIMAL TOTALS - EXPENSE MEASURED IN $') OR
    (SHORT_DESC = 'ANIMAL TOTALS BREEDING - EXPENSE MEASURED IN $') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - GAIN MEASURED IN $') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - LOSS MEASURED IN $') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - GAIN MEASURED IN $ / OPERATION') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - NET INCOME MEASURED IN $ / OPERATION') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - OPERATIONS WITH GAIN') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - OPERATIONS WITH LOSS') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - OPERATIONS WITH NET INCOME') OR 
    Short_desc LIKE '%VALUE%'
)
GROUP BY 
SHORT_DESC, COUNTY_NAME;


#'LABOR CONTRACT - EXPENSE MEASURED IN $'
#'LABOR HIRED - EXPENSE MEASURED IN $'

SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` 
FROM nassCensus2012Local WHERE 
	(/*(COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND*/ (STATE_NAME = 'Oregon')) AND
		((SHORT_DESC = 'PRACTICES LAND USE CONSERVATION EASEMENT - ACRES') OR
		(SHORT_DESC = 'PRACTICES LAND USE CONSERVATION EASEMENT - NUMBER OF OPERATIONS') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND CONSERVATION TILLAGE (EXCL NO-TILL) - ACRES') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND CONSERVATION TILLAGE NO-TILL - ACRES') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND CONVENTIONAL TILLAGE - ACRES') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND COVER CROP PLANTED (EXCL CRP) - ACRES') OR
        (SHORT_DESC = 'PRACTICES ROTATIONAL OR MGMT INTENSIVE GRAZING - NUMBER OF OPERATIONS')
)
GROUP BY 
SHORT_DESC, COUNTY_NAME;

#########################################################################################################
/*                           2007      Queries                                   */
#########################################################################################################

SELECT distinct SHORT_DESC FROM nassCensus2007Local WHERE SECTOR_DESC = "ENVIRONMENTAL" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2007Local WHERE SECTOR_DESC = "ECONOMICS" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2007Local WHERE SECTOR_DESC = "ANIMALS & PRODUCTS" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2007Local WHERE SECTOR_DESC = "DEMOGRAPHICS" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2007Local WHERE SECTOR_DESC = "CROPS" order by SHORT_DESC;



#Livestock
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%`  
FROM nassCensus2007Local WHERE 
((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon')) AND
((COMMODITY_DESC ='CATTLE') OR (COMMODITY_DESC = 'SHEEP'))
GROUP BY 
SHORT_DESC, COUNTY_NAME;


#LivestockStatewide
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%`  FROM nassCensus2007Local WHERE 
((STATE_NAME = 'Oregon')) AND
((COMMODITY_DESC ='CATTLE') OR (COMMODITY_DESC = 'SHEEP'))
GROUP BY 
SHORT_DESC, COUNTY_NAME;

#Pasture
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` FROM nassCensus2007Local WHERE 
((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon')) AND
((SHORT_DESC ='AG LAND CROPLAND PASTURED ONLY - ACRES') OR 
	(SHORT_DESC = 'AG LAND PASTURELAND (EXCL CROPLAND & WOODLAND) - ACRES') OR
    (SHORT_DESC = 'AG LAND PASTURELAND - ACRES') OR
    (SHORT_DESC = 'AG LAND WOODLAND PASTURED - ACRES')
)
GROUP BY 
SHORT_DESC, COUNTY_NAME;


#Finances
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` 
FROM nassCensus2007Local WHERE 
((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon')) AND
	((SHORT_DESC ='ANIMAL TOTALS (EXCL BREEDING) - EXPENSE MEASURED IN $') OR 
	(SHORT_DESC = 'ANIMAL TOTALS - EXPENSE MEASURED IN $') OR
    (SHORT_DESC = 'ANIMAL TOTALS BREEDING - EXPENSE MEASURED IN $') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - GAIN MEASURED IN $') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - LOSS MEASURED IN $') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - GAIN MEASURED IN $ / OPERATION') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - NET INCOME MEASURED IN $ / OPERATION') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - OPERATIONS WITH GAIN') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - OPERATIONS WITH LOSS') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - OPERATIONS WITH NET INCOME')
)
GROUP BY 
SHORT_DESC, COUNTY_NAME;


SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` 
FROM nassCensus2007Local WHERE 
	(/*(COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND*/ (STATE_NAME = 'Oregon')) AND
		((SHORT_DESC = 'PRACTICES LAND USE CONSERVATION EASEMENT - ACRES') OR
		(SHORT_DESC = 'PRACTICES LAND USE CONSERVATION EASEMENT - NUMBER OF OPERATIONS') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND CONSERVATION TILLAGE (EXCL NO-TILL) - ACRES') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND CONSERVATION TILLAGE NO-TILL - ACRES') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND CONVENTIONAL TILLAGE - ACRES') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND COVER CROP PLANTED (EXCL CRP) - ACRES') OR
        (SHORT_DESC = 'PRACTICES ROTATIONAL OR MGMT INTENSIVE GRAZING - NUMBER OF OPERATIONS')
)
GROUP BY 
SHORT_DESC, COUNTY_NAME;

###################################################################################################
/*						2002 Queries			*/
####################################################################################################


SELECT distinct SHORT_DESC FROM nassCensus2002Local WHERE SECTOR_DESC = "ENVIRONMENTAL" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2002Local WHERE SECTOR_DESC = "ECONOMICS" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2002Local WHERE SECTOR_DESC = "ANIMALS & PRODUCTS" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2002Local WHERE SECTOR_DESC = "DEMOGRAPHICS" order by SHORT_DESC;
SELECT distinct SHORT_DESC FROM nassCensus2002Local WHERE SECTOR_DESC = "CROPS" order by SHORT_DESC;



#Livestock
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%`  
FROM nassCensus2002Local WHERE 
((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon')) 
AND
((COMMODITY_DESC ='CATTLE') OR (COMMODITY_DESC = 'SHEEP'))
/*AND
DOMAIN_DESC = 'Total'*/
GROUP BY
SHORT_DESC, COUNTY_NAME;


#LivestockStatewide
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%`  FROM nassCensus2002Local WHERE 
((STATE_NAME = 'Oregon')) AND
((COMMODITY_DESC ='CATTLE') OR (COMMODITY_DESC = 'SHEEP'))
AND
DOMAIN_DESC = 'Total'
GROUP BY 
SHORT_DESC, COUNTY_NAME;

#Pasture
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` FROM nassCensus2002Local WHERE 
((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon')) AND
((SHORT_DESC ='AG LAND CROPLAND PASTURED ONLY - ACRES') OR 
	(SHORT_DESC = 'AG LAND PASTURELAND (EXCL CROPLAND & WOODLAND) - ACRES') OR
    (SHORT_DESC = 'AG LAND PASTURELAND - ACRES') OR
    (SHORT_DESC = 'AG LAND WOODLAND PASTURED - ACRES')
)
GROUP BY 
SHORT_DESC, COUNTY_NAME;


#Finances
SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` 
FROM nassCensus2002Local WHERE 
((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon')) AND
	((SHORT_DESC ='ANIMAL TOTALS (EXCL BREEDING) - EXPENSE MEASURED IN $') OR 
	(SHORT_DESC = 'ANIMAL TOTALS - EXPENSE MEASURED IN $') OR
    (SHORT_DESC = 'ANIMAL TOTALS BREEDING - EXPENSE MEASURED IN $') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - GAIN MEASURED IN $') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - LOSS MEASURED IN $') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - GAIN MEASURED IN $ / OPERATION') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - NET INCOME MEASURED IN $ / OPERATION') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - OPERATIONS WITH GAIN') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - OPERATIONS WITH LOSS') OR
    (SHORT_DESC = 'INCOME NET CASH FARM OF OPERATIONS - OPERATIONS WITH NET INCOME')
)
GROUP BY 
SHORT_DESC, COUNTY_NAME;


SELECT COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE`, `CV_%` 
FROM nassCensus2002Local WHERE 
	(/*(COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND*/ (STATE_NAME = 'Oregon')) AND
		((SHORT_DESC = 'PRACTICES LAND USE CONSERVATION EASEMENT - ACRES') OR
		(SHORT_DESC = 'PRACTICES LAND USE CONSERVATION EASEMENT - NUMBER OF OPERATIONS') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND CONSERVATION TILLAGE (EXCL NO-TILL) - ACRES') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND CONSERVATION TILLAGE NO-TILL - ACRES') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND CONVENTIONAL TILLAGE - ACRES') OR
        (SHORT_DESC = 'PRACTICES LAND USE CROPLAND COVER CROP PLANTED (EXCL CRP) - ACRES') OR
        (SHORT_DESC = 'PRACTICES ROTATIONAL OR MGMT INTENSIVE GRAZING - NUMBER OF OPERATIONS')
)
GROUP BY 
SHORT_DESC, COUNTY_NAME;




###############################################################################  TREND

SELECT row_names, COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, FREQ_DESC, `VALUE` 
FROM NASS.nassSurveyAnim2017Local 
Where COMMODITY_DESC ='CATTLE' 
	AND 
	(SHORT_DESC = 'CATTLE (EXCL COWS) - INVENTORY' OR SHORT_DESC = 'CATTLE COWS - INVENTORY')
	AND 
    ((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') AND (STATE_NAME = 'Oregon'))
    AND
    DOMAIN_DESC = 'Total'
ORDER BY COUNTY_NAME, SHORT_DESC, 'YEAR';

SELECT * 
FROM NASS.nassSurveyAnim2017Local 
Where row_names = 409754 OR row_names = 149555;


###########################################################################################################
/*			` Joins			*/
###########################################################################################################

	SELECT a.COUNTY_NAME, a.CLASS_DESC, a.SHORT_DESC, a.STATISTICCAT_DESC, a.UNIT_DESC, 
	a.FREQ_DESC, `a`.`VALUE` AS '2012 VAl', `b`.`VALUE` AS '2007 Value', /*`c`.`VALUE` AS '2002 Value', */
    `a`.`CV_%` AS '2012 CV %'
	FROM nassCensus2012Local a
    LEFT JOIN nassCensus2007Local b ON (a.COUNTY_NAME = b.COUNTY_NAME)
	LEFT JOIN nassCensus2007Local c ON (a.SHORT_DESC = c.SHORT_DESC)
    /*LEFT JOIN nassCensus2002Local c ON (a.COUNTY_NAME = c.COUNTY_NAME)
	LEFT JOIN nassCensus2002Local c ON (a.COUNTY_NAME = c.COUNTY_NAME)*/
		WHERE  DEATH
		((a.COUNTY_NAME = 'Grant' OR a.COUNTY_NAME = 'Wheeler' OR a.COUNTY_NAME = 'Gilliam') 
			AND (a.STATE_NAME = 'Oregon')) 
        AND
		((a.COMMODITY_DESC ='CATTLE') OR (a.COMMODITY_DESC = 'SHEEP'))
	ORDER BY 
	a.SHORT_DESC, a.COUNTY_NAME;
    
    
    
    
    
    
    
    /***************************************************************************************************
    ****************************         SURVEY DATA QUERIES        ************************************
    ****************************************************************************************************/
    
    SELECT * FROM NASS.nassSurveyAnim2017Local Where SHORT_DESC = 'CATTLE(EXCL COWS) - INVENTORY' OR 
	SHORT_DESC = 'CATTLE COWS - INVENTORY' 
    AND ((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') 
	AND (STATE_NAME = 'Oregon'))
	ORDER BY COUNTY_NAME, SHORT_DESC, YEAR;
    
    
    
    SELECT  row_names, COUNTY_NAME, CLASS_DESC, SHORT_DESC, STATISTICCAT_DESC, UNIT_DESC, `YEAR`, 
    FREQ_DESC, REFERENCE_PERIOD_DESC,`VALUE` 
    FROM NASS.nassSurveyAnim2017Local WHERE 
    ((COUNTY_NAME = 'Grant' OR COUNTY_NAME = 'Wheeler' OR COUNTY_NAME = 'Gilliam') 
	AND (STATE_NAME = 'Oregon'))
	ORDER BY COUNTY_NAME, SHORT_DESC, YEAR;
